name: runtime
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
version: 1.0.0-9
author: Joe Conway <joe.conway@stablekernel.com>
homepage: https://stablekernel.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  args: ^2.0.0
  pubspec: ^2.0.1
  conduit_isolate_executor:
    git: https://github.com/j4qfrost/dart-isolate-executor
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  command_line_agent:
    git: https://github.com/j4qfrost/dart-test-terminal