name: conduit_runtime
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
version: 1.0.0-b1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  args: ^2.0.0
  conduit_isolate_exec: ^1.0.0-b1
  pubspec: ^2.0.1
  yaml: ^3.1.0

dev_dependencies:
  fs_test_agent: 1.0.0-b1
  lint: ^1.5.0
  test: ^1.16.5
