name: runtime
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
version: 1.0.0-2
author: Joe Conway <joe.conway@stablekernel.com>
homepage: https://stablekernel.com

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.0 <0.50.0'
  args: ^1.5.0
  pubspec_parse: '>=0.1.4 <1.0.0'
  isolate_executor: ^2.0.0
  meta: ^1.1.5
  yaml: ^2.1.15

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  command_line_agent: ^1.0.0-b1